[UXIT-1782] Make Sponsor link required
FilecoinFoundationWeb/filecoin-foundation pull request #868
Opened 2024-11-28 14:28 UTC by barbaraperic

2024-11-28 17:27 UTC, CharlyMartin requested changes
Hi @barbaraperic 

Shouldn’t we also update the `SponsorsSchema` Zod schema to match the CMS configuration?

```ts
const sponsorSchema = z.object({
  name: z.string(),
  website: z.string().url(), // Remove .optional()
  image: ImagePropsSchema,
})
```

And If we do, we might need to backfill the data for sponsors with missing website links (I haven’t verified if any are missing)

2024-11-28 18:06 UTC, barbaraperic commented
> Hi @barbaraperic
> 
> Shouldn’t we also update the `SponsorsSchema` Zod schema to match the CMS configuration?
> 
> ```ts
> const sponsorSchema = z.object({
>   name: z.string(),
>   website: z.string().url(), // Remove .optional()
>   image: ImagePropsSchema,
> })
> ```
> 
> And If we do, we might need to backfill the data for sponsors with missing website links (I haven’t verified if any are missing)

Great points, fixed!

2024-11-29 05:56 UTC, mirhamasala commented on public/admin/config.yml
> +    required: true
This is the default.

2024-11-29 06:06 UTC, mirhamasala approved these changes
@barbaraperic - I removed [the broken link](https://filecoinfoundation.slack.com/archives/C06MTEQ3SP6/p1732859938176049). Also `required: true` is the default so removed that as well. Good to go.

2024-11-29 10:27 UTC, merged