[UXIT-1873] - Move categories and subcategory values to config.yml
FilecoinFoundationWeb/filecoin-foundation pull request #906
Opened 2024-12-10 17:54 UTC by CharlyMartin

- **Remove categories and subcategories YAML files**
- **Add categories and subcategories to config.yaml**
- **Remove ecosystem categories and subcategories directory paths**
- **Remove unused utility function getOptionsFromObject**
- **WIP**

## 📝 Description

Please include a summary of the changes. Provide context and motivation for the change, and describe what problem it solves.

- **Type:** Bug fix / New feature / Documentation / Refactor

## 🛠️ Key Changes

- [Change 1 - Brief description]
- [Change 2 - Brief description]
- ...

## 📌 To-Do Before Merging

- [ ] [Task 1 - Brief description]
- [ ] [Task 2 - Brief description]
- ...

## 🧪 How to Test

- **Setup:** [Setup details]
- **Steps to Test:**
  1. [Step 1 - Brief description]
  2. [Step 2 - Brief description]
  3. ...
- **Expected Results:** [Outcome]
- **Additional Notes:** [Additional info]

## 📸 Screenshots

Attach if there are UI changes.

## 🔖 Resources

Feel free to share any references to documentation, libraries, blog posts, or other resources that you consulted or used during the implementation of the changes.

- [Resource 1]
- [Resource 2]
- ...

2024-12-11 20:46 UTC, mirhamasala reviewed
@CharlyMartin - [This effort](https://www.notion.so/filecoin/FF-Ecosystem-Explorer-Rework-Categories-Subcategories-structure-14b7631f2825807e9ed6d87fef734eb9?pvs=4) should work in a similar way as the region implementation we did for Events.

This PR should be merged when everything is in place, that is, when the config has a single category field with just string values and the hierarchy is handled on the front. Let me know if that makes sense.

Thank you. 🙏🏼

(I did do a first review - Looking good!)

2024-12-13 06:38 UTC, mirhamasala commented
@CharlyMartin - Yes, please!

>So, I’ll create a feature branch for this effort, and from there create smaller PRs. Once everything is ready, we’ll merge the feature branch into main and everything will be in place in one go. Is that what you had in mind?

2024-12-17 09:36 UTC, CharlyMartin commented
This PR also tackles https://www.notion.so/filecoin/FF-Ecosystem-Explorer-Consolidate-getCategoriesFromDirectory-and-getCategoryDataFromDirector-1577631f28258042a0f6faa73b34acc4?pvs=4

2024-12-17 20:20 UTC, mirhamasala commented on src/app/_utils/categoryUtils.ts
> +import { type CategoryMap } from '@/types/categoryTypes'
Mega nit.

```suggestion
import type { CategoryMap } from '@/types/categoryTypes'
```

2024-12-17 20:21 UTC, mirhamasala commented on src/app/_utils/categoryUtils.ts
>  import { type CMSCollectionName } from '@/types/cmsConfig'
I thought we had something enforcing this.

```suggestion
import type { CMSCollectionName } from '@/types/cmsConfig'
```

2024-12-17 20:21 UTC, mirhamasala commented on src/app/_utils/getCMSFieldOptionsAndValidIds.ts
> +import { type CMSCollectionName } from '@/types/cmsConfig'
```suggestion
import type { CMSCollectionName } from '@/types/cmsConfig'
```

2024-12-17 20:30 UTC, mirhamasala commented on src/app/ecosystem-explorer/hooks/useEcosystemCategory.ts
Nothing to do with this for now - Might add an follow up work to refactor this.

```
import { useMemo } from 'react'
import type { NextServerSearchParams } from '@/types/searchParams'
import { CATEGORY_KEY } from '@/constants/searchParams'
import type { EcosystemProject } from '../types/ecosystemProjectType'
import { getEcosystemCMSCategories } from '../utils/getEcosystemCMSCategories'

// Types
type CategoryTreeItem = {
  value: string
  label: string
  subcategories: Array<SubcategoryWithCount>
}

type SubcategoryWithCount = {
  value: string
  label: string
  parent_category: string
  count: number
}

type UseEcosystemCategoryProps<Entry extends EcosystemProject> = {
  searchParams: NextServerSearchParams
  categories: ReturnType<typeof getEcosystemCMSCategories>['categories']
  subcategories: ReturnType<typeof getEcosystemCMSCategories>['subcategories']
  entries: Array<Entry>
}

type UseEcosystemCategoryResult<Entry> = {
  filteredEntries: Array<Entry>
  categoryTree: Array<CategoryTreeItem>
  categoryQueries: string[] | null
}

// Helper functions
function getEntriesPerSubcategory<Entry extends EcosystemProject>(
  entries: Array<Entry>
): Map<string, number> {
  const counts = new Map()
  
  entries.forEach((entry) => {
    const subcategory = entry.subcategories[0]
    counts.set(subcategory, (counts.get(subcategory) || 0) + 1)
  })
  
  return counts
}

function buildCategoryTree(
  categories: UseEcosystemCategoryProps<any>['categories'],
  subcategories: UseEcosystemCategoryProps<any>['subcategories'],
  entryCounts: Map<string, number>
): Array<CategoryTreeItem> {
  return categories.map((category) => ({
    value: category.value,
    label: category.label,
    subcategories: subcategories
      .filter((subcategory) => subcategory.parent_category === category.value)
      .map((subcategory) => ({
        ...subcategory,
        count: entryCounts.get(subcategory.value) || 0,
      })),
  }))
}

function filterEntriesByCategory<Entry extends EcosystemProject>(
  entries: Array<Entry>,
  categoryIds: string[] | null
): Array<Entry> {
  if (!categoryIds) return entries
  return entries.filter((entry) => categoryIds.includes(entry.subcategories[0]))
}

// Main hook
export function useEcosystemCategory<Entry extends EcosystemProject>({
  searchParams,
  entries,
  categories,
  subcategories,
}: UseEcosystemCategoryProps<Entry>): UseEcosystemCategoryResult<Entry> {
  const categoryParams = searchParams[CATEGORY_KEY]
  const categoryIds = parseCategoryQueryParam(categoryParams)

  const entriesPerSubcategory = useMemo(
    () => getEntriesPerSubcategory(entries),
    [entries]
  )

  const categoryTree = useMemo(
    () => buildCategoryTree(categories, subcategories, entriesPerSubcategory),
    [categories, subcategories, entriesPerSubcategory]
  )

  const filteredEntries = useMemo(
    () => filterEntriesByCategory(entries, categoryIds),
    [entries, categoryIds]
  )

  return {
    filteredEntries,
    categoryTree,
    categoryQueries: categoryIds,
  }
}
```

2024-12-17 20:37 UTC, mirhamasala commented on src/app/ecosystem-explorer/hooks/useEcosystemCategory.ts
```ts
categories.map(({ value, label }) => ({
        value,
        label,
        subcategories: subcategories
          .filter(({ parent_category }) => parent_category === value)
```

2024-12-17 20:44 UTC, mirhamasala commented on src/app/ecosystem-explorer/page.tsx
> +                        (category) => category.value === categoryId,
```suggestion
                        ({value) => value === categoryId,
```

2024-12-17 20:54 UTC, mirhamasala requested changes
Still a little confused about the order of things and the bigger picture - But trusting the process. 🔮🦀

Mostly nits - mostly Scout.

We should remove `readAndValidateYamlFiles` at this point, right?

Thank you! 🙏🏼

2024-12-17 21:07 UTC, mirhamasala commented on src/app/ecosystem-explorer/[slug]/page.tsx
> +  )
```suggestion
const projectSubcategory = findOrThrow(
  cmsSubcategories,
  ({ value }) => value === subcategories[0]
)
```

2024-12-18 10:12 UTC, CharlyMartin commented on src/app/ecosystem-explorer/schemas/CategorySchemas.ts
> +function createSchemaForField(fieldName: 'category' | 'subcategory') {
`createSchemaForField` creates a Zod schema for a given CMS field
`getCMSOptionsForField` returns an array of CMS options

2024-12-18 10:16 UTC, mirhamasala commented on src/app/ecosystem-explorer/schemas/CategorySchemas.ts
> +function createSchemaForField(fieldName: 'category' | 'subcategory') {
They both use part of the same code ad defined in `getCMSOptionsForField`..

2024-12-18 10:18 UTC, CharlyMartin commented on src/app/ecosystem-explorer/schemas/CategorySchemas.ts
> +function createSchemaForField(fieldName: 'category' | 'subcategory') {
I've put them in separate files

2024-12-18 10:20 UTC, mirhamasala commented on src/app/ecosystem-explorer/schemas/CategorySchemas.ts
> +function createSchemaForField(fieldName: 'category' | 'subcategory') {
How do you mean?

2024-12-18 10:25 UTC, CharlyMartin commented on src/app/_utils/categoryUtils.ts
> +import { type CategoryMap } from '@/types/categoryTypes'
No, you're right!

2024-12-18 10:31 UTC, CharlyMartin commented on src/app/ecosystem-explorer/schemas/CategorySchemas.ts
> +function createSchemaForField(fieldName: 'category' | 'subcategory') {
https://github.com/FilecoinFoundationWeb/filecoin-foundation/pull/906/commits/f29fdfe5280e0af2fea8efa665f2bed760c93f2a

2024-12-18 10:35 UTC, CharlyMartin commented on src/app/ecosystem-explorer/hooks/useEcosystemCategory.ts
This hook will be broken down in the next PR. The filtering will most likely be performed in `useFilter`.

Then, we can see how we can improve the rest. Does that work?

2024-12-18 10:36 UTC, CharlyMartin commented on src/app/ecosystem-explorer/hooks/useEcosystemCategory.ts
I like it :)

Let's do it in the next PR where `subcategories` becomes `subcategory`!

2024-12-18 10:37 UTC, mirhamasala commented on src/app/ecosystem-explorer/schemas/CategorySchemas.ts
> +function createSchemaForField(fieldName: 'category' | 'subcategory') {
NAISE.

2024-12-18 10:48 UTC, CharlyMartin commented
Thank you for the review @mirhamasala 

> We should remove `readAndValidateYamlFiles` at this point, right?

Definitely! Good catch!

> Mostly nits - mostly Scout.

I'm gonna try to implement some of them in the following PR :)

2024-12-18 10:49 UTC, merged