[UXIT-1793] - Ecosystem Explorer · Rework Categories/Subcategories structure
FilecoinFoundationWeb/filecoin-foundation pull request #913
Opened 2024-12-12 18:19 UTC by CharlyMartin

- **Remove categories and subcategories YAML files**
- **Add categories and subcategories to CMS config**

## 📝 Description

Please include a summary of the changes. Provide context and motivation for the change, and describe what problem it solves.

- **Type:** Bug fix / New feature / Documentation / Refactor

## 🛠️ Key Changes

- [Change 1 - Brief description]
- [Change 2 - Brief description]
- ...

## 📌 To-Do Before Merging

- [ ] [Task 1 - Brief description]
- [ ] [Task 2 - Brief description]
- ...

## 🧪 How to Test

- **Setup:** [Setup details]
- **Steps to Test:**
  1. [Step 1 - Brief description]
  2. [Step 2 - Brief description]
  3. ...
- **Expected Results:** [Outcome]
- **Additional Notes:** [Additional info]

## 📸 Screenshots

Attach if there are UI changes.

## 🔖 Resources

Feel free to share any references to documentation, libraries, blog posts, or other resources that you consulted or used during the implementation of the changes.

- [Resource 1]
- [Resource 2]
- ...

2024-12-17 14:30 UTC, mirhamasala commented on public/admin/config.yml
> +            subcategories: ["ai-productivity-utilities"]
What's is the `subcategories` field for?

2024-12-17 14:30 UTC, mirhamasala commented on public/admin/config.yml
> +            parent_category: "artificial-intelligence"
What is the `parent_category` field for? These should be removed in this PR, right?

2024-12-17 14:31 UTC, mirhamasala requested changes
@CharlyMartin Please review the comments! Thank you. 🙏🏼

2024-12-20 15:40 UTC, mirhamasala commented on src/app/ecosystem-explorer/utils/getEcosystemCMSCategories.ts
> +  const categories = getCMSFieldOptions(fields, 'category')
```suggestion
  const categoryOptions = getCMSFieldOptions(fields, 'category')
```

2024-12-20 15:40 UTC, mirhamasala commented on src/app/ecosystem-explorer/utils/getEcosystemCMSCategories.ts
> +  const categoriesWithGroup = categories.map((categoryOption) => {
```suggestion
  const categoriesWithGroup = categoryOptions.map((categoryOption) => {
```

2024-12-20 15:43 UTC, mirhamasala commented on src/app/ecosystem-explorer/utils/getEcosystemCMSCategories.ts
> +    const { category, group } = splitCategoryAndGroup(categoryOption.label)
```suggestion
    const { categoryGroup, categoryLabel } = splitCategoryGroupAndLabel(categoryOption.label)
```

2024-12-20 15:44 UTC, mirhamasala commented on src/app/ecosystem-explorer/utils/getEcosystemCMSCategories.ts
> +      label: category,
```suggestion
      label: categoryLabel,
```

2024-12-20 15:48 UTC, mirhamasala commented on src/app/ecosystem-explorer/utils/splitCategoryAndGroup.ts
> +export function splitCategoryAndGroup(label: string) {
```suggestion
export function splitCategoryAndGroup(groupAndCategoryLabel: string) {
```

2024-12-20 15:49 UTC, mirhamasala commented on src/app/ecosystem-explorer/utils/splitCategoryAndGroup.ts
> +    throw new Error(`Category label does not contain "${SEPARATOR}"`)
```suggestion
    throw new Error(`Group and category label does not contain "${SEPARATOR}"`)
```

2024-12-20 15:50 UTC, mirhamasala commented on src/app/ecosystem-explorer/utils/splitCategoryAndGroup.ts
> +  const [group, category] = label.split(SEPARATOR)
```suggestion
  const [groupLabel, categoryLabel] = groupAndCategoryLabel.split(SEPARATOR)
```

2024-12-20 15:50 UTC, mirhamasala commented on src/app/ecosystem-explorer/utils/splitCategoryAndGroup.ts
> +    throw new Error(`Category is missing from "${label}"`)
```suggestion
    throw new Error(`Category label is missing from "${label}"`)
```

2024-12-20 16:37 UTC, CharlyMartin commented
The ecosystem project form works fine https://github.com/FilecoinFoundationWeb/filecoin-foundation/pull/947

The build fails because it's merging into `main`, which doesn't contain these changes yet

2024-12-20 16:39 UTC, merged