[UXIT-1882] Filecoin Plus · Allocators Table Improvements
FilecoinFoundationWeb/filecoin-foundation pull request #953
Opened 2024-12-24 19:06 UTC by barbaraperic

## 📝 Description

This PR includes some visual improvement for the Allocators Table.

**Type:** Bug fix

## 🛠️ Key Changes

- [x]  Make Filters fixed
- [x]  Add a border around the table
- [x]  Make the organization name column sticky
- [x]  Elipsify organization name (with browser tooltip)
- [x]  Link organization name to apply link
- [x]  Remove apply link

## 📌 To-Do

- [ ] Make Table Header fixed

## 📸 Screenshots

https://github.com/user-attachments/assets/2be55f80-98f1-45b2-b65b-aff68bb29e7c

2024-12-31 17:07 UTC, CharlyMartin approved these changes
To test again after mono-repo is merged https://github.com/FilecoinFoundationWeb/filecoin-foundation/pull/970

2025-01-02 15:13 UTC, mirhamasala commented on apps/site/src/app/_components/Listbox/ListboxOptions.tsx
> +        'z-50 min-w-[var(--button-width)] rounded-lg border border-brand-100 bg-brand-800 py-2 text-brand-100 focus:brand-outline focus-within:outline-2',
I find it odd to set `z-50` on this component? It's like we are reaching in..

2025-01-02 15:16 UTC, mirhamasala requested changes
@CharlyMartin - Things are looking a little off. Also, I don't the double sticky header is looking like expected. Let's pair so I can explain a bit more!

![CleanShot 2025-01-02 at 15 15 29@2x](https://github.com/user-attachments/assets/a3641b23-afe7-42ed-837c-f5a63aee4004)

![CleanShot 2025-01-02 at 15 14 25@2x](https://github.com/user-attachments/assets/cccd390c-1769-48d1-a59c-d4e53cf976fd)

![CleanShot 2025-01-02 at 15 14 10@2x](https://github.com/user-attachments/assets/cd6f337b-c6c2-4aa0-b9f2-cff7b203a372)

2025-01-03 13:43 UTC, mirhamasala commented on apps/site/src/app/security/bug-bounty/components/Leaderboard.tsx
> +    <Table freezeHeader>
Should probably be the default for all tables, no?

2025-01-03 13:43 UTC, mirhamasala commented on apps/site/src/app/filecoin-plus/allocators/components/AllocatorsTableWithFilters.tsx
> +    <div className="isolate">
No need anymore.

2025-01-03 16:46 UTC, merged